name: Run Cypress Component Tests

on:
  push:
    branches:
      - production

jobs:
  cypress-component-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Backend
        run: |
          cd server
          npm run build

      - name: Seed Backend Data
        run: |
          cd server
          npm run seed

      - name: Start Backend Service
        run: |
          cd server
          npm start &
          sleep 10 # Wait for backend to initialize

      - name: Start Frontend Service
        run: |
          cd client
          npm run dev &
          sleep 10 # Wait for frontend to initialize

      - name: Run Cypress Component Tests
        run: npm run test-component
