name: Run Cypress Component Tests

on:
  push:
    branches:
      - production

jobs:
  cypress-component-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Debug Command
        run: echo "Test workflow triggered successfully"
