name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Start Backend Service
        run: |
          cd server
          npm start &
          sleep 10 # Wait for backend to start

      - name: Start Frontend Service
        run: |
          cd client
          npm run dev &
          sleep 10 # Wait for frontend to start

      - name: Run Cypress Tests
        run: |
          cd client
          npm run test

