name: Run Cypress Component Tests

on:
  push:
    branches:
      - develop

jobs:
  cypress-component-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Cypress Component Tests
      - name: Run Cypress Component Tests
        run: npm run test-component


