# .github/workflows/test.yml
name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Start services
        run: |
          cd server
          npm start &
          cd ../client
          npm run dev &
        shell: bash

      - name: Run Cypress Tests
        run: |
          cd client
          npm run test
